name: expense-tracker

services:
  # TODO: each service might want to have its own database?
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=pw

  service.auth:
    depends_on:
      - postgres
    build:
      context: ./service.auth
      dockerfile: Dockerfile
    volumes:
      - ./service.auth:/docker/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST="postgres"
      - DB_USERNAME="postgres"
      - DB_PASSWORD="pw"
      - PORT=8000

  service.ledger:
    depends_on:
      - postgres
    build:
      context: ./service.ledger
      dockerfile: Dockerfile
    volumes:
      - ./service.ledger:/docker/app
    ports:
      - "8001:8001"
    environment:
      - DB_HOST="postgres"
      - DB_USERNAME="postgres"
      - DB_PASSWORD="pw"
      - PORT=8001
